config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :rewards, :pledges
    resources :comments, only: [:show, :create, :destroy]
  end

  resources :tags
  resources :users
  resources :sessions


  get 'login'   => 'sessions#new',    :as => :login
  post 'logout' => 'sessions#destroy',:as => :logout
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name, :end_date, :funding_goal, :description

  belongs_to :owner, class_name: 'User'
  has_many :backers, through: :pledges, class_name: 'User', foreign_key: 'backer_id'
  has_many :pledges
  has_many :rewards
  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true
  has_many :pledges, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :comments

  mount_uploader :feature_image, FeatureImageUploader


  def add_tag(tag)
    self.tags << tag unless self.tags.include?(tag)
  end

  def days_remaining
    ((self.end_date.end_of_day - Time.now.beginning_of_day) / 86400).to_i
  end

  def fully_funded?
    self.pledges.all.sum(:amount) >= self.funding_goal
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def index
    @pledges = Pledge.all

    if params[:proj_search] == nil && params[:tag_search] == nil
      @projects = Project.all
      @tags = Tag.all
    elsif params[:proj_search]
      @projects = Project.where("LOWER(name) LIKE LOWER(?)", "#{params[:proj_search]}%")
      @tags = []
      @projects.each do |project|
        project.tags.each { |tag| @tags << tag unless @tags.include?(tag) }
      end
    elsif params[:tag_search]
      @tags = Tag.where("LOWER(name) LIKE LOWER(?)", "#{params[:tag_search]}%")
      @projects = []
      @tags.each do |tag|
        tag.projects.each { |project| @projects << project unless @projects.include?(project) }
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @project = Project.find(params[:id])
    @tags = @project.tags.order(name: :asc)

    if @project.pledges.find_by(backer_id: current_user)
      @pledge = @project.pledges.find_by(backer_id: current_user)
    else
      @pledge = Pledge.new
    end

    if current_user
      @comment = Comment.new
    end

    respond_to do |format|
      format.html
      format.js
    end


  end

  def new
    @project = Project.new
    @project.rewards.build
  end

  def create
    @project = Project.create(project_params)
    @project.owner = current_user

    if @project.save
      flash[:notice] = "Project successfully created!"
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @tags = @project.tags.order(name: :asc)

    if params[:tag]
      @project.tags.delete(params[:tag])
      return
    end

    if params[:project][:tags]
      @tag = Tag.find(params[:project][:tags])
      @project.add_tag(@tag)
      redirect_to project_path(@project)
      return
    end

    if @project.update_attributes(project_params)
      flash[:notice] = "Project successfully edited."
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project successfully deleted."
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :end_date, :funding_goal, :description, :feature_image, rewards_attributes:
        [:name, :price, :description, :number_available, :project_id, :_destroy])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_tag_form.html.erb
<%= form_for @project, remote: true, html: { id: "add-tag" } do |f| %>
  <%= f.collection_select :tags, Tag.all.order(name: :asc), :id, :name %>
  <%= f.submit "Add Tag" %>
<% end %>

app/views/projects/_comments.html.erb
<% @project.comments.order(created_at: :desc).each do |comment|  %>

    <p>
      <%= comment.message %>
      <br>

      <% if comment.user != nil  %>
          <em> by <%= comment.user.username %></em>
          Added on: <%= comment.created_at %>
      <% end %>

<% end %>

app/views/projects/_edit_pledge.html.erb
<%= form_for [@project, @pledge] do |f| %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount, value: @pledge.amount %>
    <%= "   " %>
    <%= link_to "Delete This Pledge", [@project, @pledge], method: :delete, data: {confirm: "Are you sure you want to delete this pledge?"} %>
  </div>

  <div class="action">
    <%= f.submit "Submit your pledge" %>
  </div>

<% end %>

app/views/projects/_project.html.erb
<li><%= link_to project.name, project_path(project) %>, created by <i><%= link_to project.owner.username, user_path(project.owner) %></i></li>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :number_available %>
    <%= f.number_field :number_available %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= link_to_remove_association "Remove Reward", f %>
</div>

app/views/projects/edit.html.erb
<% if @project.owner == current_user %>
  <h1>Edit <%= @project.name %></h1>

  <%= form_for @project do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, value: @project.name %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, value: @project.end_date.strftime("%Y-%m-%d") %>
  </div>

  <div class="field">
    <%= f.label :funding_goal %>
    <%= f.number_field :funding_goal, value: @project.funding_goal %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, value: @project.description %>
  </div>

  <div class="action">
    <%= f.submit "Update Project" %>
  </div>

  <% end %>

  <%= link_to "Delete This Project", @project, method: :delete, data: {confirm: "Are you sure you want to delete this project?"} %>

<% else %>
  <%= controller.redirect_to project_path, notice: "Access to edit project denied!" %>
<% end %>

app/views/projects/index.html.erb
<p><b>
  To date: <%= @pledges.count %> backers,
  $<%= @pledges.all.sum(:amount) %> raised,
  and <%= @projects.select { |project| project.fully_funded? }.count %>
  projects fully funded
</b></p>

<div>
  <% if current_user %>
    <%= link_to "Add a Project", new_project_path %>
  <% else %>
      <p>Please login to add a project</p>
  <% end %>
</div>


<div class="show-projects">

  <div id="project-search-form">
    <%= form_tag root_path, method: :get, remote: true, id: 'proj-search-form' do %>
    <%= text_field_tag :proj_search, params[:proj_search] %>
    <%= submit_tag "Search projects" %>
    <% end %>
  </div>

  <% if @projects.any? %>
    <h4>All Projects</h4>
    <div id="project-list">
      <%= render @projects %>
    </div>
  <% else %>
    <p>No projects yet!</p>
  <% end %>
</div>

<div class="show-tags">

  <div id="tag-search-form">
    <%= form_tag root_path, method: :get, remote: true, id: 'tag-search-form' do %>
    <%= text_field_tag :tag_search, params[:tag_search] %>
    <%= submit_tag "Search tags" %>
    <% end %>
  </div>

  <% if @tags.any? %>
    <h4>All Tags</h4>
    <div id="tag-list">
      <%= render @tags %>
    </div>
  <% else %>
    <p>No tags yet!</p>
  <% end %>
</div>

app/views/projects/index.js.erb
$('#project-list').html('<%= j(render @projects) %>')
$('#tag-list').html('<%= j(render @tags) %>')

app/views/projects/new.html.erb
<h1>Create a New Project</h1>

<%= form_for @project do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :funding_goal %>
    <%= f.number_field :funding_goal %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :feature_image %>
    <%= f.file_field :feature_image %>
  </div>

  <h3>Rewards</h3>
    <div id="rewards">
      <%= f.fields_for :rewards do |reward_fields| %>
        <%= render "reward_fields", f: reward_fields %>

        <div class="links">
          <%= link_to_add_association "Add another reward", f, :rewards %>
        </div>

      <% end %>
    </div>

  <div class="action">
    <%= f.submit "Create New Project" %>
  </div>

<% end %>

app/views/projects/show.html.erb
<%= image_tag @project.feature_image.feature.url %>

<h1><%= @project.name %></h1>

<p><b>There are <%= @project.days_remaining %> days left before this project expires</b></p>


<ul>
  <li>Funding Goal: $<%= @project.funding_goal %></li>
  <li>End Date: <%= @project.end_date.strftime("%A, %d %b %Y %l:%M %p") %></li>
  <li>Project Owner: <%= @project.owner.first_name + " " + @project.owner.last_name %></li>
  <li>About the project:
    <p><%= @project.description %></p>
  </li>
</ul>

<% if @project.tags != nil %>
  <div class="list-tags">
    <%= render @tags %>
  </div>
<% end %>

<% if @project.owner == current_user %>
  <div class="add-tags">
    <%= render 'add_tag_form' %>
  </div>
<% end %>

<div class="rewards">
  <h3>Rewards!</h3>
  <% @project.rewards.each do |reward| %>
  <p>
    Amount: $<%= reward.price %><br>
    Reward Tier: <%= reward.name %><br>
    Number Available: <%= reward.number_available%><br>
    Description: <%= reward.description %><br>
  </p>
  <% end %>
</div>

<div class="pledge-info">

  <h3>Total pledges for this project: $<span id="total-pledges"><%= @project.pledges.all.sum(:amount) %></span>.00</h3>
  <h4>Distance to Goal: $<span id="distance-to-goal"><%= @project.funding_goal - @project.pledges.all.sum(:amount) %></span>.00</h4>

  <div class="pledge_form">
    <% if @project.pledges.find_by(backer_id: current_user) %>
      <p>You've already backed this project.</p>
      <p>You've pledged $<%= @project.pledges.find_by(backer_id: current_user).amount %>.00</p>
      <p>Update your pledge:</p>
      <%= form_for [@project, @pledge] do |f| %>

        <div class="field">
          <%= f.label :amount %>
          <%= f.number_field :amount, value: @pledge.amount %>
          <%= "   " %>
          <%= link_to "Delete This Pledge", [@project, @pledge], method: :delete, data: {confirm: "Are you sure you want to delete this pledge?"} %>
        </div>

        <div class="action">
          <%= f.submit "Submit your pledge" %>
        </div>

      <% end %>
    <% else %>
      <p>Pledge to this project:</p>
      <%= form_for [@project, @pledge], id: "new-pledge" do |f| %>
      <div class="field">
        <%= f.label :amount %>
        <%= f.number_field :amount %>
      </div>

      <div class="action">
        <%= f.submit %>
      </div>
      <% end %>
    <% end %>
  </div>



</div>

<div>
  <% if @project.owner == current_user %>
  <%= render "pledges/index" %>
  <br>
  <%= link_to "Edit or Delete this project", edit_project_path %>
  <% end %>
</div>

<div>
  <%= render "comments/form" %>
</div>

<div id="comments_list">
  <%= render "comments" %>
</div>

app/views/projects/show.js.erb
$('.list-tags').html('<%= j(render @tags) %>');

app/views/projects/update.js.erb
$('.list-tags').html('<%= j(render @tags) %>');