config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :rewards, :pledges
    resources :comments, only: [:show, :create, :destroy]
  end

  resources :tags
  resources :users
  resources :sessions


  get 'login'   => 'sessions#new',    :as => :login
  post 'logout' => 'sessions#destroy',:as => :logout
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name
  has_and_belongs_to_many :projects
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :load_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def show
    @projects = @tag.projects.order('projects.created_at DESC').page(params[:page])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    # figure out how to titleize name before it is saved to the db

    if @tag.save
      redirect_to tags_path, notice: "Tag created successfully"
    else
      render :new, notice: "Tag not created"
    end
  end

  def edit
  end

  def update
    if @tag.update_attributes(tag_params)
      redirect_to tag_path(@tag), notice: "Tag updated"
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: "Tag removed"
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

  def load_tag
    @tag = Tag.find(params[:id])
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag.html.erb
<div class="tag-link">
  <%= link_to "#{tag.name}", tag_path(tag) %>
</div>

<% unless request.original_url == projects_url || request.original_url == root_url %>
  <div class="untag-link">
    <% if @project.owner == current_user %>
      <%= form_for @project, remote: true, html: { id: "remove-tag" } do |f| %>
        <%= hidden_field_tag :tag, tag.id %>
        <%= f.submit "X" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag:</h1>

<%= form_for @tag do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="action">
    <%= f.submit "create tag" %>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1>Project Categories:</h1>

<p><%= link_to "Add a tag", new_tag_path %></p>

<div class="display-tags">
  <% if @tags.any? %>
    <% @tags.sort_by { |tag| tag.name }.each do |tag| %>
      <li><%= link_to "#{tag.name}", tag_path(tag) %></li>
    <% end %>
  <% else %>
    <h3>No tags yet...</h3>
  <% end %><br>
</div>

app/views/tags/new.html.erb
<h1>Create a Tag:</h1>

<%= form_for @tag do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="action">
    <%= f.submit "create tag" %>
  </div>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<%= link_to "Edit tag", edit_tag_path(@tag) %>

<h3>Items tagged as <i><%= @tag.name %></i>...</h3>

<div class="display-tagged-projects">
  <% if @tag.projects.any? %>
    <%= render @projects %>
  <% else %>
    <p>No projects...</p>
  <% end %>
</div>

<%= paginate @projects %>