config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :rewards, :pledges
    resources :comments, only: [:show, :create, :destroy]
  end

  resources :tags
  resources :users
  resources :sessions


  get 'login'   => 'sessions#new',    :as => :login
  post 'logout' => 'sessions#destroy',:as => :logout
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Dosis|Josefin+Slab' rel='stylesheet' type='text/css'>
</head>
<body>

  <div id="nav">

    <h1><%= link_to "Crowdfunder", root_path %></h1>

    <div class="user-links">
      <% if current_user && !current_page?(user_path(current_user.id)) %>
        <%= link_to "User Page", user_path(current_user.id) %> |
      <% end %>
      <% if current_user %>
          <%= link_to "Logout", :logout, method: :post %>
      <% else %>
          <%= link_to "Register", new_user_path %> |
          <%= link_to "Login", :login %>
      <% end %>
    </div>

    <div class="nav-links">
      <%= link_to "Home", root_path %> |
      <%= link_to "Projects", projects_path %> |
      <%= link_to "Categories", tags_path %>
    </div>

    <div class="flash-notifications">
      <p id="alert"><%= flash[:alert] %></p>
      <p id="alert"><%= flash[:notice] %></p>
    </div>
    
  </div>



  <div id="page-content">
    <%= yield %>
  </div>


  <footer>
    <% unless current_page?('/projects') %>
      <%= link_to "Back to Project List", projects_path %> |
    <% end %>
    <% unless current_page?('/tags') %>
      <%= link_to "Tags", tags_path %><br>
    <% end %>
    2016 - Mike Bowman, Steve O'Neil, Patrick Cruikshank, Matthew Smith &copy;
  </footer>
</body>
</html>